### ISSUE TITLE
发现了一个可能的bug

### ISSUE THREAD

**Issue by zhuwenbing** [MikeCoder/hexo-blog-encrypt#11]
重复多次得出的结果：password如果使用数字，必需添加引号，否则报错，字母的反而可以不加引号

**Comment by zhuwenbing** [comment]
错误信息：
```
TypeError: Cannot read property '0' of undefined
    at Object.xorBlock (C:\Users\Administrator\photo\node_modules\crypto-js\ciph
er-core.js:369:44)
    at Object.processBlock (C:\Users\Administrator\photo\node_modules\crypto-js\
cipher-core.js:314:27)
    at Object._doProcessBlock (C:\Users\Administrator\photo\node_modules\crypto-
js\cipher-core.js:477:25)
    at Object._process (C:\Users\Administrator\photo\node_modules\crypto-js\core
.js:585:27)
    at Object._doFinalize (C:\Users\Administrator\photo\node_modules\crypto-js\c
ipher-core.js:490:50)
    at Object.finalize (C:\Users\Administrator\photo\node_modules\crypto-js\ciph
er-core.js:163:44)
    at Object.encrypt (C:\Users\Administrator\photo\node_modules\crypto-js\ciphe
r-core.js:670:41)
    at Object.encrypt (C:\Users\Administrator\photo\node_modules\crypto-js\ciphe
r-core.js:201:59)
    at Hexo.<anonymous> (C:\Users\Administrator\photo\node_modules\hexo-blog-enc
rypt\index.js:62:37)
    at Hexo.tryCatcher (C:\Users\Administrator\photo\node_modules\bluebird\js\re
lease\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Administrator\photo\node_modules\bluebird\js\r
elease\method.js:15:34)
    at C:\Users\Administrator\photo\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (C:\Users\Administrator\photo\node_modules\bluebird\js\release
\util.js:16:23)
    at Object.gotValue (C:\Users\Administrator\photo\node_modules\bluebird\js\re
lease\reduce.js:155:18)
    at Object.gotAccum (C:\Users\Administrator\photo\node_modules\bluebird\js\re
lease\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\Administrator\photo\node_modules\bluebird\js\
release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\photo\node_modu
les\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Administrator\photo\node_modules\bluebir
d\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Administrator\photo\node_modules\bluebi
rd\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Administrator\photo\node_modules\bluebi
rd\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Administrator\photo\node_modules\bluebird\js\
release\async.js:138:16)
    at Async._drainQueues (C:\Users\Administrator\photo\node_modules\bluebird\js
\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Users\Administrator\photo\node_modules\bl
uebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FATAL Cannot read property '0' of undefined
```

**Comment by D0n9X1n** [comment]
收到，估计 js 把纯数字直接当做数字来处理了，但是加解密这边需要字符串。

谢谢！

**Comment by D0n9X1n** [comment]
`npm update` 升级到 v1.1.10，应该解决了这个 bug。

测试网址：[http://mikecoder.github.io/2016/12/23/Example/](http://mikecoder.github.io/2016/12/23/Example/)

**Comment by zhuwenbing** [comment]
@MikeCoder 赞，这么快就解决了
