### ISSUE TITLE
当 post页面 Font-matter 里的password为空时，报错。

### ISSUE THREAD

**Issue by Peter-Duan** [MikeCoder/hexo-blog-encrypt#124]
```FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'toString' of null
    at Hexo.hexo.extend.filter.register (D:\HexoBlog\hexo\node_modules\hexo-blog-encrypt\index.js:50:23)
    at Hexo.tryCatcher (D:\HexoBlog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\HexoBlog\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (D:\HexoBlog\hexo\node_modules\hexo\lib\extend\filter.js:60:50)
    at tryCatcher (D:\HexoBlog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\HexoBlog\hexo\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (D:\HexoBlog\hexo\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (D:\HexoBlog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\HexoBlog\hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\HexoBlog\hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\HexoBlog\hexo\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\HexoBlog\hexo\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\HexoBlog\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\HexoBlog\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\HexoBlog\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\HexoBlog\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

![image](https://user-images.githubusercontent.com/48420970/70295057-96836600-17b3-11ea-8f6d-882c56d72789.png)

顺便还发现了彩蛋QWQ

![image](https://user-images.githubusercontent.com/48420970/70295087-b9ae1580-17b3-11ea-88a1-9118d520c953.png)

**Comment by D0n9X1n** [comment]
v3.0.6 修好了.

PS: 这不是彩蛋, 这是事实(一本正经).
