### ISSUE TITLE
安装插件后hexo g报错 TypeError: data.tags.forEach is not a function

### ISSUE THREAD

**Issue by Destiny-Lu** [MikeCoder/hexo-blog-encrypt#189]
# Issue
After installing the plugin and configuring it according to the manual, execute hexo g to report an error **TypeError: data.tags.forEach is not a function**
## Expected Behavior
normal program execution
## Actual Behavior
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  hexo-blog-encrypt: encrypting "test" based on the password configured in Front-matter with theme: default.
FATAL {
  err: TypeError: data.tags.forEach is not a function
      at Hexo.<anonymous> (D:\Blog\blog\node_modules\hexo-blog-encrypt\index.js:53:15)
      at Hexo.tryCatcher (D:\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (D:\Blog\blog\node_modules\bluebird\js\release\method.js:15:34)
      at D:\Blog\blog\node_modules\hexo\lib\extend\filter.js:67:52
      at tryCatcher (D:\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (D:\Blog\blog\node_modules\bluebird\js\release\reduce.js:166:18)
      at Object.gotAccum (D:\Blog\blog\node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (D:\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Blog\blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Blog\blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Blog\blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Blog\blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\Blog\blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\Blog\blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\Blog\blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\Blog\blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:466:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

## Steps to Reproduce the Problem

1. npm install --save hexo-blog-encrypt
2. hexo clean
3. hexo g

## Specifications
$ npm list
hexo-site@0.0.0 D:\Blog\blog
├── hexo-blog-encrypt@3.1.6
├── hexo-deployer-git@3.0.0
├── hexo-filter-ignore-formula-rendering@0.0.2
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index-pin-top@0.2.2
├── hexo-generator-json-content@4.2.3
├── hexo-generator-searchdb@1.4.0
├── hexo-generator-tag@1.0.0
├── hexo-generator-topindex@0.3.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3
└── hexo@6.2.0

$ node -v
v16.15.0

windows11
(The version of the project, operating system, hardware etc.)

**Comment by Destiny-Lu** [comment]
是我的tags/index.md写错了

**Comment by EthanLiu6** [comment]
怎么处理的
