### ISSUE TITLE
報錯……

### ISSUE THREAD

**Issue by ShinoharaYuri** [MikeCoder/hexo-blog-encrypt#4]
Node version(node -v)

>  v6.7.0

Plugin version(`npm ls --depth 0`)

> hexo-site@0.0.0 /root/Blog
> ├── hexo@3.2.2
> ├── hexo-blog-encrypt@1.1.4
> ├── hexo-deployer-ftpsync@0.1.1
> ├── hexo-deployer-git@0.2.0
> ├── hexo-deployer-rsync@0.1.2
> ├── hexo-generator-archive@0.1.4
> ├── hexo-generator-category@0.1.3
> ├── hexo-generator-feed@1.2.0
> ├── hexo-generator-index@0.2.0
> ├── hexo-generator-search@1.0.2
> ├── hexo-generator-seo-friendly-sitemap@0.0.19
> ├── hexo-generator-tag@0.2.0
> ├── hexo-renderer-ejs@0.2.0
> ├── hexo-renderer-marked@0.2.11
> ├── hexo-renderer-stylus@0.3.1
> └── hexo-server@0.2.0

``` nodejs
INFO  Start processing
encrypt the blog :1
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property '0' of undefined
    at Object.xorBlock (/root/Blog/node_modules/crypto-js/cipher-core.js:369:44)
    at Object.processBlock (/root/Blog/node_modules/crypto-js/cipher-core.js:314:27)
    at Object._doProcessBlock (/root/Blog/node_modules/crypto-js/cipher-core.js:477:25)
    at Object._process (/root/Blog/node_modules/crypto-js/core.js:567:27)
    at Object._doFinalize (/root/Blog/node_modules/crypto-js/cipher-core.js:490:50)
    at Object.finalize (/root/Blog/node_modules/crypto-js/cipher-core.js:163:44)
    at Object.encrypt (/root/Blog/node_modules/crypto-js/cipher-core.js:670:41)
    at Object.encrypt (/root/Blog/node_modules/crypto-js/cipher-core.js:201:59)
    at Hexo.<anonymous> (/root/Blog/node_modules/hexo-blog-encrypt/index.js:55:37)
    at Hexo.tryCatcher (/root/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/root/Blog/node_modules/bluebird/js/release/method.js:15:34)
    at /root/Blog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/root/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/root/Blog/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/root/Blog/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/root/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/root/Blog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/root/Blog/node_modules/bluebird/js/release/async.js:148:10)
FATAL Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Object.xorBlock (/root/Blog/node_modules/crypto-js/cipher-core.js:369:44)
    at Object.processBlock (/root/Blog/node_modules/crypto-js/cipher-core.js:314:27)
    at Object._doProcessBlock (/root/Blog/node_modules/crypto-js/cipher-core.js:477:25)
    at Object._process (/root/Blog/node_modules/crypto-js/core.js:567:27)
    at Object._doFinalize (/root/Blog/node_modules/crypto-js/cipher-core.js:490:50)
    at Object.finalize (/root/Blog/node_modules/crypto-js/cipher-core.js:163:44)
    at Object.encrypt (/root/Blog/node_modules/crypto-js/cipher-core.js:670:41)
    at Object.encrypt (/root/Blog/node_modules/crypto-js/cipher-core.js:201:59)
    at Hexo.<anonymous> (/root/Blog/node_modules/hexo-blog-encrypt/index.js:55:37)
    at Hexo.tryCatcher (/root/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/root/Blog/node_modules/bluebird/js/release/method.js:15:34)
    at /root/Blog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/root/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/root/Blog/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/root/Blog/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/root/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/root/Blog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/root/Blog/node_modules/bluebird/js/release/async.js:148:10)
```

**Comment by D0n9X1n** [comment]
It seems like 'crypto-js' lib crushed when encrypting your post data. 
Can you provide your `_config.yml` content and your blog encrypted setting?

**Comment by D0n9X1n** [comment]
Try to update the plugin from v1.1.4 to v1.1.5

**Comment by ShinoharaYuri** [comment]
Thx

**Comment by ShinoharaYuri** [comment]
JTNDcCUzRTQ2ODQ4NjQ1JTNDL3AlM0UlMEE=

解密之後 內容變成這樣……
