### ISSUE TITLE
输入密码后报错

### ISSUE THREAD

**Issue by hinbang** [MikeCoder/hexo-blog-encrypt#64]
用的是next主题，一切都看似正常，
可是当我输入密码成功进入文章时，
并没有显示文章内容，而是有一句提示“Some errors occurred, check the original file please.Detailed exception are shown in console.”

**Comment by D0n9X1n** [comment]
贴一下 console 里面的日志.

**Comment by hinbang** [comment]
206:Markdown_to_Git cxb$ hexo g
INFO  Start processing
INFO  Files loaded in 678 ms
INFO  Generated: categories/FPGA/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2018/12/index.html
INFO  Generated: about/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: archives/2018/index.html
INFO  Generated: archives/2019/01/index.html
INFO  Generated: tags/index.html
INFO  Generated: categories/FPGA/IP-Core/index.html
INFO  Generated: 2018/12/22/IP_DDR3/index.html
INFO  Generated: categories/index.html
INFO  Generated: 2019/01/08/Computer-network/index.html
INFO  Generated: 2019/01/06/实现内网穿透/index.html
INFO  Generated: 2018/12/22/foolish-everyday/index.html
INFO  Generated: index.html
INFO  Generated: lib/blog-encrypt.js
INFO  Generated: css/blog-encrypt.css
INFO  Generated: lib/crypto-js.js
INFO  18 files generated in 962 ms
206:Markdown_to_Git cxb$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
[master d217678] Site updated: 2019-01-15 00:47:09
 15 files changed, 38 insertions(+), 97 deletions(-)
warning: redirecting to https://github.com/hinbang/hinbang.github.io.git/
To http://github.com/hinbang/hinbang.github.io.git
   6368062..d217678  HEAD -> master
Branch 'master' set up to track remote branch 'master' from 'http://github.com/hinbang/hinbang.github.io.git'.
INFO  Deploy done: git
206:Markdown_to_Git cxb$ 

这是我的网页  http://chenxuanbang.cn/2019/01/06/实现内网穿透       密码：174811

**Comment by hinbang** [comment]
实在不好意思，我没有找到console的日志
我只是在macos自带的终端下generate和deploy

**Comment by D0n9X1n** [comment]
原因找到了，因为你的文章内部引用了 flowchart，这个没有预先加载。

你要改一下这篇文章的模板, 参考[这个](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E4%BF%AE%E6%94%B9%E5%8A%A0%E5%AF%86%E6%A8%A1%E6%9D%BF), 使用下面的针对单篇文章的修改方式，修改内容如下，引入头两个 js 文件：

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"/>
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js/">
<div id="hbe-security">
  <div class="hbe-input-container">
  <input type="password" class="hbe-form-control" id="pass" placeholder="{{message}}" />
    <label for="pass">{{message}}</label>
    <div class="bottom-line"></div>
  </div>
</div>
<div id="decryptionError" style="display:none;">{{decryptionError}}</div>
<div id="noContentError" style="display:none;">{{noContentError}}</div>
<div id="encrypt-blog" style="display:none">
{{content}}
</div>
```

**Comment by D0n9X1n** [comment]
这是个临时解决办法，这个 bug 下一版本解决。

**Comment by hinbang** [comment]
### 17行内容 
“<div id="decryptionError"style="display: none;">{{decryptionError}}</div>”

### 终端报错
chenxuanbangdeMacBook-Pro:Markdown_to_Git cxb$ hexo s
INFO  Start processing
ERROR Process failed: _posts/实现内网穿透.md
YAMLException: bad indentation of a mapping entry at line 17, column 42:
     ... ="decryptionError"style="display: none;">{{decryptionError}}</div>
                                         ^
    at generateError (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:1080:7)
    at composeNode (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/Users/cxb/Markdown_to_Git/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at parseYAML (/Users/cxb/Markdown_to_Git/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/Users/cxb/Markdown_to_Git/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/Users/cxb/Markdown_to_Git/node_modules/hexo/lib/plugins/processor/post.js:51:20)
    at tryCatcher (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/cxb/Markdown_to_Git/node_modules/bluebird/js/release/promise.js:614:10)
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

**Comment by D0n9X1n** [comment]
`“<div id="decryptionError"style="display: none;">{{decryptionError}}”` 

`display: none` 的空格去掉变成 `display:none` .

你可以把文章 `---` 之间的配置到 `https://www.bejson.com/validators/yaml_editor/` 这边检测下是否符合 YAML 规范.

比如这样的:
```
title: hello world
date: 2016-03-30 21:18:02
tags:
    - fdsfadsfa
    - fdsafsdaf
password: Mike
abstract: Welcome to my blog, enter password to read.
message: Welcome to my blog, enter password to read.
template:
          <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
          <div id="hbe-security">
            <div class="hbe-input-container">
            <input type="password" class="hbe-form-control" id="pass" placeholder="{{message}}" />
              <label for="pass">{{message}}</label>
              <div class="bottom-line"></div>
            </div>
          </div>
          <div id="decryptionError" style="display:none;">{{decryptionError}}</div>
          <div id="noContentError" style="display:none;">{{noContentError}}</div>
          <div id="encrypt-blog" style="display:none">
          {{content}}
          </div>
```

**Comment by hinbang** [comment]
学到了，太谢谢了。
不过修改完后，点进博客连密码提示框也不出现了。
 http://chenxuanbang.cn/2019/01/06/实现内网穿透

**Comment by D0n9X1n** [comment]
模板写错. 第一个 js tag 没有关闭 `<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js">` 后面要加 `</script>` 结尾.

直接贴这个.

```
template:
          <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"></script>
          <div id="hbe-security">
            <div class="hbe-input-container">
            <input type="password" class="hbe-form-control" id="pass" placeholder="{{message}}" />
              <label for="pass">{{message}}</label>
              <div class="bottom-line"></div>
            </div>
          </div>
          <div id="decryptionError" style="display:none;">{{decryptionError}}</div>
          <div id="noContentError" style="display:none;">{{noContentError}}</div>
          <div id="encrypt-blog" style="display:none">
          {{content}}
          </div>

```

**Comment by hinbang** [comment]
work，太感谢了

**Comment by hubelief** [comment]
我遇到一个js文件的一个报错：
ReferenceError: $ is not defined    ------blog-encrypt.js
求助。。。

**Comment by hubelief** [comment]
求助
